#!/bin/bash



# This is a temporary workaround until this issue is resolved:
# https://github.com/openshift/origin-server/issues/6390
cd ${OPENSHIFT_REPO_DIR}/website
pip install -r requirements.txt --no-cache-dir