#!/bin/bash


source $OPENSHIFT_PYTHON_DIR/virtenv/bin/activate

cd ${OPENSHIFT_REPO_DIR}/website

python manage.py migrate
python manage.py collectstatic --noinput

# This is a temporary workaround until this issue is resolved:
# https://github.com/openshift/origin-server/issues/6390
pip install -r requirements.txt --no-cache-dir