#!/bin/bash

if [ ! -f $OPENSHIFT_DATA_DIR/old_matches_lock ]; then
  touch $OPENSHIFT_DATA_DIR/old_matches_lock
fi
if [[ $(find $OPENSHIFT_DATA_DIR/old_matches_lock -mmin +9) ]]; then #run every 10 mins
  rm -f $OPENSHIFT_DATA_DIR/old_matches_lock
  touch $OPENSHIFT_DATA_DIR/old_matches_lock

  # The command(s) that you want to run every 10 minutes
  source $OPENSHIFT_PYTHON_DIR/virtenv/bin/activate
  cd ${OPENSHIFT_REPO_DIR}/website
  make update_matches backwards=true fails_limit=200
fi